### ISSUE TITLE
Dude, how the hell did you do the CodeGolf Pi problem????  

### ISSUE THREAD

**Issue by brendansaliba** [primo-ppcg/bf-jit#1]
Dude, how the hell did you do the CodeGolf Pi problem????  In 58 characters!

**Comment by primo-ppcg** [comment]
I suppose you mean in Python? There are many possible methods for computing π to arbitrary precision, for example Euler-Leibniz:

π = 2 + 1/3 × (2 + 2/5 × (2 + 3/7 × (2 + 4/9 × (2 + 5/11 × (2 + ... ([wolframalpha](https://www.wolframalpha.com/input/?i=sum+%7B+2+n%21+%2F+%282n+%2B+1%29%21%21+%7D+n+%3D+0..infty))

a sample imlementation of which might look something like this:

```python
x = 1
for p in range(3321, 0, -1):
  x = p*x//(2*p+1)+2*10**1000
print(x)
```

[Try it online!](https://tio.run/##Fco7DoAgEAXAnlO8kp@Bhc7Ew1j4oYENocDTr1pMN/yMu9UsMrGB1Nk6GKWi7/U6dM6JPKLHQmZVwJ/YzhB0suzIuGQp2k@MinupQ08j8gI "Python 3 – Try It Online")
